# Configuración general del bot
simulation: true
initial_balance:
  USDT: 10000
  BTC: 1
  ETH: 10
slippage_range: [0.0001, 0.001]  # 0.01% - 0.1%
partial_fill_range: [0.7, 1.0]
fee: 0.001  # 0.1%
log_interval: 10  # segundos
